spring:
  datasource:
    hikari:
      username: postgres
      password: 1234
    url: jdbc:tc:postgresql:///test-database?stringtype=unspecified
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect